{% set name = "py-bash-completion" %}
{% set version = "0.2.3" %}
{% set sha256 = "5f60efb02b51fb9a1fb45902130bd3508a1e9f82c535cbb7f0ae1986ef6108e0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/b/bash_completion/bash_completion-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - bash_completion

about:
  home: https://github.com/xonsh/py-bash-completion
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A framework for accessing bash completions from Python'

extra:
  recipe-maintainers:
    - scopatz
