{% set name = "py-bash-completion" %}
{% set version = "0.2.8" %}
{% set sha256 = "e7a9ee1963dd4f4304fda1cb93519872b57579c6940c0a2710f66b8be0031c7b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/b/bash_completion/bash_completion-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - bash_completion

about:
  home: https://github.com/xonsh/py-bash-completion
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A framework for accessing bash completions from Python

extra:
  recipe-maintainers:
    - scopatz
