{% set name = "py-bash-completion" %}
{% set version = "0.2.7" %}
{% set sha256 = "c26492ca073739fe1a1aa0c50c3fa62639d892776a074a383e068ab550ec6bf0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/b/bash_completion/bash_completion-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - bash_completion

about:
  home: https://github.com/xonsh/py-bash-completion
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A framework for accessing bash completions from Python

extra:
  recipe-maintainers:
    - scopatz
