travis:
  secure:
    BINSTAR_TOKEN: wg2a73LOwsqlvBf3E5liy3jmUmTmVDrYMFHpXQhTkmFRK5/uRJw22qxYTdbjzK8LHsd6yQx6Xt3butsxiVV/eLn5akkXPu9qgQSPjQDLMzIqmVVIXaAuUHfN+LFWgGn0teAVA3aPUPNA4wH8txGKSJBIjdpcLvXQo0FPQ3ucjYNC9oYaA4CR8B8T1fCIAkA2MroADqpWhRBzznnLUl/cb5FXUq8xhERKVXYM0M7Wn9v6/zLnxKPw47tHmUA7+tUcv4K+JbDXO+QsnmU9RJw9+IANWuLECBPzpoOmJ6m32s3Lqacf1eaCj4qXemqp0B3d+AerQNvYaj+8o4+uRU/Y0CNbUgIC3fZzzzX93PWbPSuyGW7RsFMUKIgl+0lpjeDBdsl98TlRWUVoyPd0HKRXc8jzsAAWF5E38kQhxoPVnqvI2hN6s1N7iSe65+/yWBqEYYKf0QllIIDGZQ4tXBbu6zc4n9euzJ9uwrczFizKBXTIldjjVosNO/olSEtg4d6NhPl9eV5uYR+HB96ygrpTebokwFQWW3C6moeHgX3MoknloVG/PB0QPz2phakAP9IvZXg4CtClGC6/Far5IGGrTX642it5leoitpsX64K6mtUP4S98UgkOACV2RD07nT2ScyAYovuVj3PF1F4YzQTd9pFq4gl/zOmVl+SkzPck8ZU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
