travis:
  secure:
    BINSTAR_TOKEN: 1rrUAUBiccSmxJrgLRcKWIM2aTQeMu4/uhnK6MeZaWJZTAVY/j1PLwETYu+8vEskzVvvYkj2OvbjlxVKmcY/wQYKPxgk7PgMCzucNsRly6VxBzXV88bzteisl3+2ZkyGEwNwNCzFIc1OwpLwz7l3hgRfz4l5dsDdNpmpSdSlWQRtjf4vKjv2QsMjfEgUZ3zNkGsbPYPeqm2sAwwGVKKZ+Yw7DUaLRC/Yk6IboI4DJwLhXQEODLTN4wGNHMKs732NW42ZNqPfs0wszInIfpMh7UfjOJ7VUo+aP3u0xrSEN0L6/b82ecObJ4uKB97bOzFVYhRn8WhAcbAnF1od9INipsytsKuUy9McIfXitkUbHCH9GQGIZEanbROyPYUH2ksNVsXlq4+kEuppZPUAk1S+SC5v3/0nJ6NZZknGI+gjLANDOEZ9kbSeMCwVxAA5AAk90qAKHU83nO6mtdZsZrW0mvmFX6McFo+6J2M36PnDMfBedtV4TT1wJ/sPT07r2ULSZlTiOXyxEdTPyyUYidHVknsuaBsgwBCAg2LKgPNmvGi4SsyaE42pcMY6xMfO9FP/BZaFcLjDL7VjKR7oI37DtqIFDg2YPGxKeDFql97TEvXvahQxvaOI7x+ltX+7YiofJ5vOQQt/DAK5nqaNerCINz/6ecsBC5YonKTENroOz+8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
